### ISSUE TITLE
Migration of the Inflector to Support OAS 3.0

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-inflector#202]
#This ticket has the activities related to the Migration of the inflector in order tu support 3.0.

**TODO:**

- [x] Refactor logic in OpenAPIOperationController, to support 3.0. **Dev. Time 4 h** 
- [x] Refactor Tests and testing OpenAPIOperationController **Test Time 4h**
- [x] Refactor logic in DefaultController to support 3.0 **Dev. Time 4 h** 
- [x] Refactor Tests and testing DefaultController **Test Time 4 h**
- [x] Refactor logic in ExampleBuilder to support 3.0 **Dev. Time 4 h** 
- [x] Refactor Tests and testing Example Builder **Test Time 4 h**
- [x] Check the example models to add or remove if necessary **Dev. Time 1 h** 
- [x] Refactor Tests and testing example Models **Test Time 1 h**
- [x] Migrate the test from models, refactor if necessary **Dev. Time 1 h** - **Test Time 4 h**
- [x] Migrate the test from Processors, refactor if necessary **Dev. Time 1 h** - **Test Time 4 h**
- [x] SpecFilters: Learn how the new spec filters are being implement and change the functionality in 
       the inflector **Dev. Time 4 h**
- [x] Refactor Tests and testing SpecFilters **Test Time 4h**
- [x] Resolver Fully: functionality migrated to parser and the extensions remain at the inflector.
- [x] Refactor Logic in every validator to support 3.0 **Dev. Time 4 h** 
- [x] Refactor Tests and testing in validators **Test Time 4h**
- [x] Refactor Logic in OpenAPIInflector. **Dev. Time 4 h** 
- [x] Refactor Tests and testing OpenAPIInflector **Test Time 4h**
- [x] Refactor Integration tests. 8h
- [x] Add functionality to support requestBodies

**Comment by gracekarina** [comment]
@webron The implementation of the inflector is done for this first scope, what's missing:
1.Handling form Data parameters (which have changed)
2.Adapting spec filters

**Comment by gracekarina** [comment]
The spec filters are working
